### ISSUE TITLE
Question about the architecture of resnet-20 in the paper

### ISSUE THREAD

**Issue by Albert0147** [ustc-vim/dualnet#3]
Does the number of output channels vary from 64->128->256->512 just like the origin ResNet paper?

**Comment by hshustc** [comment]
As stated in the paper, the implementation of ResNet-20 refers to https://github.com/twtygqyy/resnet-cifar10/tree/master/resnet20 with slight modification for CIFAR100.

**Comment by Albert0147** [comment]
Thanks a lot!
