### ISSUE TITLE
训练60000次后，损失函数降不下来，结果的精度很低

### ISSUE THREAD

**Issue by Victorieahui** [ustc-vim/dualnet#4]
你好，最近一直在读你的这篇文章，用caffe跑程序，迭代完60000次后，损失函数从最开始的7.67降到3.76左右（学习率也调整过，batchsize调整为3），训练完后，精度只有12%左右，我想请教下，怎么修改源程序参数呢？才能使损失函数收敛，精度有论文中那么高。。。期待你的答复，谢谢

**Comment by Victorieahui** [comment]
还有S1、S2两个通道是怎么融合的，code部分没看到是怎么融合的，可以指导下吗

**Comment by hshustc** [comment]
1.即使用单个网络finetune训练的结果也不可能只有12%，应该是你的训练过程或者数据有误，请仔细检查。
2. S1和S2是通过SUM融合的，参见train_val.prototxt。

**Comment by Victorieahui** [comment]
你好！我微调了CaffeNet原始网络之后，测试的精度是64.35%，和文中66.84%有些许差异。
你的预训练模型是在ImageNet训练过的吗？
还是仅仅是在CaffeNet对初始数据进行训练，没有微调？

**Comment by Victorieahui** [comment]
你好！我微调了CaffeNet原始网络之后，测试的精度是64.35%，和文中66.84%有些许差异。
你的预训练模型是在ImageNet训练过的吗？
还是仅仅是在CaffeNet对初始数据进行训练，没有微调？
