### ISSUE TITLE
Does the net is defined purely by protxt? 

### ISSUE THREAD

**Issue by ZhiweiYan-96** [ustc-vim/dualnet#5]
Hi,hshustc!

        Thanks for your great work.  Could you tell me if you use python API to define DualNet?  It seeems that no python file in your project is used to define DualNet.  I only see the protxtfile.  Hope get ur response, thanks.

**Comment by hshustc** [comment]
I modified the method to initialize the network from a pretrained model, which is included in src/caffe/net.cpp.

**Comment by hshustc** [comment]
Actually the implementation for DualNet is simple. You can also try it with pycaffe or other frameworks for deep learning.

**Comment by ZhiweiYan-96** [comment]
thxs for your response!
